### ISSUE TITLE
pip install fails

### ISSUE THREAD

**Issue by bartek** [dmw/pyxser#1]
When I run

```
 pip install pyxser
```

It looks like the reference no longer works.

---

Downloading/unpacking pyxser
  HTTP error 404 while getting http://coder.cl/download/pyxser-1.5.2-r2.tar.gz (from http://pypi.python.org/simple/pyxser/)
  Could not install requirement pyxser because of error HTTP Error 404: Not Found
Could not install requirement pyxser because of HTTP error HTTP Error 404: Not Found for URL http://coder.cl/download/pyxser-1.5.2-r2.tar.gz (from http://pypi.python.org/simple/pyxser/)
Storing complete log in /Users/bartekc/.pip/pip.log

**Comment by niedbalski** [comment]
HI bartek,

Daniel Molina , the Pyxser's author died a few months ago. Apparently nobody handles his pypi credentials so i am afraid that you have to generate the Pyxser distribution by yourself.

**Comment by bartek** [comment]
@niedbalski I am very sorry to here that. Thank you for the reply
